# Docker schema version definition
# Check the compatibility matrix with the current schema version in the File Creation Reference.
# https://docs.docker.com/compose/compose-file/
version: "3.8"

# Services or Containers List definition
services:
  synabro:
    container_name: synabro_backend
    image: springio/gs-spring-boot-docker
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
  mariadb:
    container_name: synabroDB
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    restart: always