spring:
  devtools:
    add-properties: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/synabro
    username: synabroUser
    password: synabroPassword*
  jpa:
    hibernate:
      ddl-auto: update