spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/{db_name}
    username: {username}
    password: {password}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\\a\\SynabroBackend\\src\\main\\resources\\static\\images\\
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

