spring:
  devtools:
    add-properties: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://synabroDB:3306/{database_name}
    username: {user_name}
    password: {user_password}
  jpa:
    hibernate:
      ddl-auto: update