spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/synabro
    username: synabroUser
    password: synabroPassword*
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /docs
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher